# Generated by Django 5.2.1 on 2025-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Приоритет")),
            ],
            options={
                "verbose_name": "приоритет",
                "verbose_name_plural": "Приоритеты",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название проекта"),
                ),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="ReadyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Статус готовности"),
                ),
            ],
            options={
                "verbose_name": "статус готовности",
                "verbose_name_plural": "Статусы готовности",
            },
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("time_estimation", models.TimeField(verbose_name="Оценка времени")),
                ("spent_time", models.TimeField(verbose_name="Затраченное время")),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название подзадачи"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название тэга"),
                ),
            ],
            options={
                "verbose_name": "тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("time_estimation", models.TimeField(verbose_name="Оценка времени")),
                ("spent_time", models.TimeField(verbose_name="Затраченное время")),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название задачи"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KanbanBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название доски"),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanbanboards",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
