# Generated by Django 5.2.1 on 2025-06-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="developers",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Исполнители"
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="priority",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.priority",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="projects.tag", verbose_name="Теги"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="developers",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Исполнители"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="kanboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.kanbanboard",
                verbose_name="Доска",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.priority",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ready_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.readystatus",
                verbose_name="Статус готовности",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="projects.tag", verbose_name="Теги"
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="tasks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="projects.task",
                verbose_name="Задание",
            ),
        ),
    ]
